### ISSUE TITLE
Allow to set debug level of sshd

### ISSUE THREAD

**Issue by frankhommers** [efrecon/rsshd#3]
I would like to to specify debug level through a `-e DEBUG_LEVEL=<level>`

Ideally it would:
* Behave as is now when absent or `-e DEBUG_LEVEL=0`
* Pass `-d` to sshd when `-e DEBUG_LEVEL=1`
* Pass `-d -d` to sshd when `-e DEBUG_LEVEL=2`
* Pass `-d -d -d` to sshd when `-e DEBUG_LEVEL>=3`

`-e SSHD_PARAMS=<extra_commandline_args>`
Could be a possibility too!

**Comment by efrecon** [comment]
All "options" that you pass to the container are given further to `sshd`, this is a perfect place for giving options. So running with something similar to the following should do the trick:

````
docker run ... efrecon/rsshd -oxxx
````
