### ISSUE TITLE
EOL error

### ISSUE THREAD

**Issue by hr1179** [efrecon/rsshd#4]
When trying to run the container, I got this error message: standard_init_linux.go:190: exec user process caused "exec format error"
According to https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory this could be a EOL issue.

**Comment by hr1179** [comment]
Building the image again solves the issue

**Comment by efrecon** [comment]
I forced a rebuilt at the hub, and changed the endings of the Dockerfile. The shell script had proper endings. Let me know if it helps, I close this for now though.
